name: Continuous Deployment
on:
  push:
    branches:
      - main

jobs:
  test:
    name: Execute Node Native Tests Locally
    runs-on: debian-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Dependencies for Testing
        run: npm install

      - name: Run Node Tests Instantly
        run: npm run test
